package at.steinbacher.geckopose

import at.steinbacher.geckoposelib.data.*
import com.google.mlkit.vision.pose.PoseLandmark

val cyclingConfiguration = listOf(
    GeckoPoseConfiguration(
        tag = "left_pose",
        pointConfigurations = listOf(
            PointConfiguration(PoseLandmark.LEFT_HIP),
            PointConfiguration(PoseLandmark.LEFT_KNEE),
            PointConfiguration(PoseLandmark.LEFT_ANKLE),
            PointConfiguration(PoseLandmark.LEFT_SHOULDER),
            PointConfiguration(PoseLandmark.LEFT_ELBOW),
            PointConfiguration(PoseLandmark.LEFT_WRIST),
        ),
        lineConfigurations = listOf(
            LineConfiguration(start = PoseLandmark.LEFT_KNEE, end = PoseLandmark.LEFT_HIP, tag = "knee_hip"),
            LineConfiguration(start = PoseLandmark.LEFT_ANKLE, end = PoseLandmark.LEFT_KNEE, tag = "knee_ankle"),
            LineConfiguration(start = PoseLandmark.LEFT_HIP, end = PoseLandmark.LEFT_SHOULDER, tag = "hip_shoulder"),
            LineConfiguration(start = PoseLandmark.LEFT_SHOULDER, end = PoseLandmark.LEFT_ELBOW, tag = "shoulder_elbow"),
            LineConfiguration(start = PoseLandmark.LEFT_ELBOW, end = PoseLandmark.LEFT_WRIST, tag = "elbow_wrist"),
        ),
        angleConfigurations = listOf(
            AngleConfiguration(startPointType = PoseLandmark.LEFT_HIP, middlePointType = PoseLandmark.LEFT_KNEE,
                endPointType = PoseLandmark.LEFT_ANKLE, tag = "a"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_KNEE, middlePointType = PoseLandmark.LEFT_HIP,
                endPointType = PoseLandmark.LEFT_SHOULDER, tag = "b"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_HIP, middlePointType = PoseLandmark.LEFT_SHOULDER,
                endPointType = PoseLandmark.LEFT_ELBOW, tag = "c"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_SHOULDER, middlePointType = PoseLandmark.LEFT_ELBOW,
                endPointType = PoseLandmark.LEFT_WRIST, tag = "d"),
        ),
    ),
    GeckoPoseConfiguration(
        tag = "right_pose",
        pointConfigurations = listOf(
            PointConfiguration(PoseLandmark.RIGHT_HIP),
            PointConfiguration(PoseLandmark.RIGHT_KNEE),
            PointConfiguration(PoseLandmark.RIGHT_ANKLE),
            PointConfiguration(PoseLandmark.RIGHT_SHOULDER),
            PointConfiguration(PoseLandmark.RIGHT_ELBOW),
            PointConfiguration(PoseLandmark.RIGHT_WRIST),
        ),
        lineConfigurations = listOf(
            LineConfiguration(start = PoseLandmark.RIGHT_KNEE, end = PoseLandmark.RIGHT_HIP, tag = "knee_hip"),
            LineConfiguration(start = PoseLandmark.RIGHT_ANKLE, end = PoseLandmark.RIGHT_KNEE, tag = "knee_ankle"),
            LineConfiguration(start = PoseLandmark.RIGHT_HIP, end = PoseLandmark.RIGHT_SHOULDER, tag = "hip_shoulder"),
            LineConfiguration(start = PoseLandmark.RIGHT_SHOULDER, end = PoseLandmark.RIGHT_ELBOW, tag = "shoulder_elbow"),
            LineConfiguration(start = PoseLandmark.RIGHT_ELBOW, end = PoseLandmark.RIGHT_WRIST, tag = "elbow_wrist"),
        ),
        angleConfigurations = listOf(
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_HIP, middlePointType = PoseLandmark.RIGHT_KNEE,
                endPointType = PoseLandmark.RIGHT_ANKLE, tag = "a"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_KNEE, middlePointType = PoseLandmark.RIGHT_HIP,
                endPointType = PoseLandmark.RIGHT_SHOULDER, tag = "b"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_HIP, middlePointType = PoseLandmark.RIGHT_SHOULDER,
                endPointType = PoseLandmark.RIGHT_ELBOW, tag = "c"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_SHOULDER, middlePointType = PoseLandmark.RIGHT_ELBOW,
                endPointType = PoseLandmark.RIGHT_WRIST, tag = "d"),
        ),
    )
)

val tennisConfiguration = listOf(
    GeckoPoseConfiguration(
        tag = "main_pose",
        pointConfigurations = listOf(
            PointConfiguration(PoseLandmark.LEFT_SHOULDER),
            PointConfiguration(PoseLandmark.LEFT_ELBOW),
            PointConfiguration(PoseLandmark.LEFT_WRIST),
            PointConfiguration(PoseLandmark.RIGHT_SHOULDER),
            PointConfiguration(PoseLandmark.RIGHT_ELBOW),
            PointConfiguration(PoseLandmark.RIGHT_WRIST),
            PointConfiguration(PoseLandmark.LEFT_HIP),
            PointConfiguration(PoseLandmark.RIGHT_HIP),
            PointConfiguration(PoseLandmark.LEFT_KNEE),
            PointConfiguration(PoseLandmark.RIGHT_KNEE),
            PointConfiguration(PoseLandmark.LEFT_ANKLE),
            PointConfiguration(PoseLandmark.RIGHT_ANKLE),

            ),
        lineConfigurations = listOf(
            LineConfiguration(start = PoseLandmark.LEFT_SHOULDER, end = PoseLandmark.LEFT_ELBOW, tag = "left_shoulder_elbow"),
            LineConfiguration(start = PoseLandmark.LEFT_ELBOW, end = PoseLandmark.LEFT_WRIST, tag = "left_elbow_wrist"),
            LineConfiguration(start = PoseLandmark.LEFT_SHOULDER, end = PoseLandmark.RIGHT_SHOULDER, tag = "shoulder_shoulder"),
            LineConfiguration(start = PoseLandmark.RIGHT_SHOULDER, end = PoseLandmark.RIGHT_ELBOW, tag = "right_shoulder_elbow"),
            LineConfiguration(start = PoseLandmark.RIGHT_ELBOW, end = PoseLandmark.RIGHT_WRIST, tag = "right_elbow_wrist"),
            LineConfiguration(start = PoseLandmark.RIGHT_SHOULDER, end = PoseLandmark.RIGHT_HIP, tag = "right_shoulder_hip"),
            LineConfiguration(start = PoseLandmark.LEFT_SHOULDER, end = PoseLandmark.LEFT_HIP, tag = "left_shoulder_hip"),
            LineConfiguration(start = PoseLandmark.LEFT_HIP, end = PoseLandmark.LEFT_KNEE, tag = "left_hip_shoulder"),
            LineConfiguration(start = PoseLandmark.LEFT_HIP, end = PoseLandmark.RIGHT_HIP, tag = "left_hip_right_hip"),
            LineConfiguration(start = PoseLandmark.RIGHT_HIP, end = PoseLandmark.RIGHT_KNEE, tag = "right_hip_shoulder"),
            LineConfiguration(start = PoseLandmark.LEFT_KNEE, end = PoseLandmark.LEFT_ANKLE, tag = "left_knee_ankle"),
            LineConfiguration(start = PoseLandmark.RIGHT_KNEE, end = PoseLandmark.RIGHT_ANKLE, tag = "right_knee_ankle"),
        ),
        angleConfigurations = listOf(
            AngleConfiguration(startPointType = PoseLandmark.LEFT_SHOULDER, middlePointType = PoseLandmark.LEFT_ELBOW,
                endPointType = PoseLandmark.LEFT_WRIST, tag = "left_a"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_SHOULDER, middlePointType = PoseLandmark.RIGHT_ELBOW,
                endPointType = PoseLandmark.RIGHT_WRIST, tag = "right_a"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_ELBOW, middlePointType = PoseLandmark.LEFT_SHOULDER,
                endPointType = PoseLandmark.LEFT_HIP, tag = "left_b"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_HIP, middlePointType = PoseLandmark.RIGHT_SHOULDER,
                endPointType = PoseLandmark.RIGHT_ELBOW, tag = "right_b"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_SHOULDER, middlePointType = PoseLandmark.LEFT_HIP,
                endPointType = PoseLandmark.LEFT_KNEE, tag = "left_c"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_KNEE, middlePointType = PoseLandmark.RIGHT_HIP,
                endPointType = PoseLandmark.RIGHT_SHOULDER, tag = "right_c"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_ANKLE, middlePointType = PoseLandmark.LEFT_KNEE,
                endPointType = PoseLandmark.LEFT_HIP, tag = "left_d"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_ANKLE, middlePointType = PoseLandmark.RIGHT_KNEE,
                endPointType = PoseLandmark.RIGHT_HIP, tag = "right_d"),
        ),
        poseCenterPointsTargets = listOf(PoseLandmark.LEFT_SHOULDER, PoseLandmark.RIGHT_SHOULDER, PoseLandmark.LEFT_HIP, PoseLandmark.RIGHT_HIP)
    ),
    GeckoPoseConfiguration(
        tag = "main_pose",
        pointConfigurations = listOf(
            PointConfiguration(PoseLandmark.LEFT_SHOULDER),
            PointConfiguration(PoseLandmark.LEFT_ELBOW),
            PointConfiguration(PoseLandmark.LEFT_WRIST),
            PointConfiguration(PoseLandmark.RIGHT_SHOULDER),
            PointConfiguration(PoseLandmark.RIGHT_ELBOW),
            PointConfiguration(PoseLandmark.RIGHT_WRIST),
            PointConfiguration(PoseLandmark.LEFT_HIP),
            PointConfiguration(PoseLandmark.RIGHT_HIP),
            PointConfiguration(PoseLandmark.LEFT_KNEE),
            PointConfiguration(PoseLandmark.RIGHT_KNEE),
            PointConfiguration(PoseLandmark.LEFT_ANKLE),
            PointConfiguration(PoseLandmark.RIGHT_ANKLE),

            ),
        lineConfigurations = listOf(
            LineConfiguration(start = PoseLandmark.LEFT_SHOULDER, end = PoseLandmark.LEFT_ELBOW, tag = "left_shoulder_elbow"),
            LineConfiguration(start = PoseLandmark.LEFT_ELBOW, end = PoseLandmark.LEFT_WRIST, tag = "left_elbow_wrist"),
            LineConfiguration(start = PoseLandmark.LEFT_SHOULDER, end = PoseLandmark.RIGHT_SHOULDER, tag = "shoulder_shoulder"),
            LineConfiguration(start = PoseLandmark.RIGHT_SHOULDER, end = PoseLandmark.RIGHT_ELBOW, tag = "right_shoulder_elbow"),
            LineConfiguration(start = PoseLandmark.RIGHT_ELBOW, end = PoseLandmark.RIGHT_WRIST, tag = "right_elbow_wrist"),
            LineConfiguration(start = PoseLandmark.RIGHT_SHOULDER, end = PoseLandmark.RIGHT_HIP, tag = "right_shoulder_hip"),
            LineConfiguration(start = PoseLandmark.LEFT_SHOULDER, end = PoseLandmark.LEFT_HIP, tag = "left_shoulder_hip"),
            LineConfiguration(start = PoseLandmark.LEFT_HIP, end = PoseLandmark.LEFT_KNEE, tag = "left_hip_shoulder"),
            LineConfiguration(start = PoseLandmark.LEFT_HIP, end = PoseLandmark.RIGHT_HIP, tag = "left_hip_right_hip"),
            LineConfiguration(start = PoseLandmark.RIGHT_HIP, end = PoseLandmark.RIGHT_KNEE, tag = "right_hip_shoulder"),
            LineConfiguration(start = PoseLandmark.LEFT_KNEE, end = PoseLandmark.LEFT_ANKLE, tag = "left_knee_ankle"),
            LineConfiguration(start = PoseLandmark.RIGHT_KNEE, end = PoseLandmark.RIGHT_ANKLE, tag = "right_knee_ankle"),
        ),
        angleConfigurations = listOf(
            AngleConfiguration(startPointType = PoseLandmark.LEFT_SHOULDER, middlePointType = PoseLandmark.LEFT_ELBOW,
                endPointType = PoseLandmark.LEFT_WRIST, tag = "left_a"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_SHOULDER, middlePointType = PoseLandmark.RIGHT_ELBOW,
                endPointType = PoseLandmark.RIGHT_WRIST, tag = "right_a"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_ELBOW, middlePointType = PoseLandmark.LEFT_SHOULDER,
                endPointType = PoseLandmark.LEFT_HIP, tag = "left_b"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_HIP, middlePointType = PoseLandmark.RIGHT_SHOULDER,
                endPointType = PoseLandmark.RIGHT_ELBOW, tag = "right_b"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_SHOULDER, middlePointType = PoseLandmark.LEFT_HIP,
                endPointType = PoseLandmark.LEFT_KNEE, tag = "left_c"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_KNEE, middlePointType = PoseLandmark.RIGHT_HIP,
                endPointType = PoseLandmark.RIGHT_SHOULDER, tag = "right_c"),
            AngleConfiguration(startPointType = PoseLandmark.LEFT_ANKLE, middlePointType = PoseLandmark.LEFT_KNEE,
                endPointType = PoseLandmark.LEFT_HIP, tag = "left_d"),
            AngleConfiguration(startPointType = PoseLandmark.RIGHT_ANKLE, middlePointType = PoseLandmark.RIGHT_KNEE,
                endPointType = PoseLandmark.RIGHT_HIP, tag = "right_d"),
        ),
        poseCenterPointsTargets = listOf(PoseLandmark.LEFT_SHOULDER, PoseLandmark.RIGHT_SHOULDER, PoseLandmark.LEFT_HIP, PoseLandmark.RIGHT_HIP)
    )
)